# Generated by Django 2.0.1 on 2018-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('expires_in', models.PositiveSmallIntegerField()),
                ('token_type', models.CharField(max_length=25)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
