# Generated by Django 2.0.1 on 2018-01-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User_data',
        ),
    ]
