# Generated by Django 2.0.1 on 2018-01-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180130_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_date',
            new_name='User_data',
        ),
    ]
