# Generated by Django 2.0.1 on 2018-01-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180130_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_data',
            new_name='UserData',
        ),
    ]
